### ISSUE TITLE
failed on make

### ISSUE THREAD

**Issue by andyyuan78** [alfonsoros88/ScaRF#1]
ubgpu@ubgpu:~/github/ScaRF/build$ sudo make
-- Boost version: 1.54.0
-- Configuring done
CMake Error at /usr/local/share/cmake-3.2/Modules/FindCUDA.cmake:1561 (add_executable):
  Cannot find source file:

```
/home/ubgpu/github/ScaRF/samples/sowerby/main.cu
```

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
Call Stack (most recent call first):
  samples/CMakeLists.txt:6 (cuda_add_executable)

-- Generating done
-- Build files have been written to: /home/ubgpu/github/ScaRF/build
make: **\* [cmake_check_build_system] Error 1
ubgpu@ubgpu:~/github/ScaRF/build$

**Comment by rosds** [comment]
Hi, I didn't include that particular sample. I made all the samples optional so it can compile. Thanks for reporting this issue.
